services:
  chatdb:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc@12345
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - chatdb

volumes:
  chat_postgres_data:
